import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqlite3/sqlite3.dart';
import 'package:yem_erp/src/application/app_services.dart';
import 'package:yem_erp/src/application/invoice_pdf_service.dart';
import 'package:yem_erp/src/application/local_auth_service.dart';
import 'package:yem_erp/src/data/local_migrations.dart';
import 'package:yem_erp/src/domain/identifiers.dart';
import 'package:yem_erp/src/domain/money.dart';
import 'package:yem_erp/src/domain/sales_invoice.dart';
import 'package:yem_erp/src/infrastructure/invoice_pdf_renderer.dart';
import 'local_auth_test.dart' show TestHasher;

void main(){
  TestWidgetsFlutterBinding.ensureInitialized();late Database db;late AppServices app;late String id,company;
  const password='LongPassword123!';
  setUp(()async{
    db=sqlite3.openInMemory();db.execute('PRAGMA foreign_keys=ON');await LocalMigrations.apply(db);app=AppServices(LocalAuthService(db,TestHasher()));
    await app.auth.bootstrap(companyName:'مؤسسة يمن للتجارة',branchName:'صنعاء',username:'admin',password:password);company=app.companies.single.id;await app.auth.login(companyId:company,username:'admin',password:password);app.sales.configureDefaults();
    final branch=app.sales.branches().single.id,product=app.products.create(unitId:app.units.single.id,name:'خدمة صيانة الأجهزة',sku:'SERVICE-01',isStockItem:false).id;
    db.execute("INSERT INTO customers(id,company_id,name,created_at) VALUES('c',?,'شركة الأمل','date')",[company]);
    id=app.sales.create(id:newUuid(),branch:branch,customer:'c',isCash:true,cash:app.sales.cashAccounts().single.id,date:'2026-10-05',description:'خدمة صيانة وفق الاتفاق',lines:[InvoiceLineDraft(productId:product,quantity:2,unitPrice:Money(125050))]);
  });
  tearDown(()=>db.close());
  test('stored invoice renders an embedded-font PDF without modifying journals',()async{
    final before=app.posting.entries().length;
    final bytes=await app.invoicePdf.generate(id);
    expect(ascii.decode(bytes.take(5).toList()),'%PDF-');expect(bytes.length,greaterThan(5000));
    final text=latin1.decode(bytes);expect(text,contains('/FontFile2'));expect(text,contains('/ToUnicode'));expect(app.posting.entries(),hasLength(before));
    expect(()=>app.invoicePdf.generate('foreign'),throwsA(isA<AccessDenied>()));
  });
  test('permission revocation while rendering denies generated bytes',()async{
    final pending=Completer<Uint8List>();final renderer=InvoicePdfService(app.auth,app.sales,render:(_)=>pending.future);
    final result=renderer.generate(id);final assertion=expectLater(result,throwsA(isA<AccessDenied>()));
    db.execute("DELETE FROM role_permissions WHERE permission_code='sales.view'");pending.complete(Uint8List.fromList([1,2,3]));await assertion;
  });
  test('logout and re-login to same user invalidates pending PDF',()async{
    final pending=Completer<Uint8List>();final renderer=InvoicePdfService(app.auth,app.sales,render:(_)=>pending.future);
    final result=renderer.generate(id);final assertion=expectLater(result,throwsA(isA<AccessDenied>()));
    app.auth.logout();await app.auth.login(companyId:company,username:'admin',password:password);pending.complete(Uint8List.fromList([1,2,3]));await assertion;
  });
  test('fifty long Arabic rows paginate and emit visual QA fixture',()async{
    final sample=SalesInvoice(id:newUuid(),number:'SI-00000050',date:'2026-10-05',companyName:'مؤسسة يمن للتجارة والخدمات',branchName:'الفرع الرئيسي - صنعاء',customerName:'شركة الأمل للتجارة',description:'فاتورة اختبار بصري لسلامة الخط العربي والأرقام وتكرار عناوين الجدول عبر الصفحات.',totalMinor:6252500,isCash:false,items:List.generate(50,(i)=>InvoiceItem(productId:'p-$i',name:'خدمة صيانة وتجهيز الأجهزة والمعدات للمؤسسات - البند ${i+1}',sku:'SERVICE-${(i+1).toString().padLeft(3,'0')}',unitName:'وحدة',quantity:1,unitPriceMinor:125050,totalMinor:125050,costMinor:0,isStockItem:false)));
    final bytes=await InvoicePdfRenderer().render(sample);final text=latin1.decode(bytes);
    expect(RegExp(r'/Type\s*/Page\b').allMatches(text).length,greaterThan(1));
    final directory=Directory('build/test-output');await directory.create(recursive:true);await File('${directory.path}/invoice-arabic-qa.pdf').writeAsBytes(bytes);
  });
}
